config/routes.rb
Rails.application.routes.draw do
  # Disallow registration, wire up custom devise sessions controller
  devise_for :users, skip: [:registrations], controllers: { sessions: :sessions }

  devise_scope :user do
    # Manually re-creates routes for editing users
    get 'users/edit' => 'devise/registrations#edit', as: :edit_user_registration
    put 'users' => 'devise/registrations#update', as: :user_registration
  end

  namespace :admin do
    resources :basic_projects, path: 'basic-projects'
    resources :calendar, only: [:index]
    resources :calendar_events, only: [:index]
    resources :loan_response_sets
    resources :divisions do
      collection do
        post :select
      end
    end
    resources :loans do
      member do
        get :questionnaires
        get :print
        get :duplicate
      end
    end
    resources :loan_questions do
      patch 'move', on: :member
    end
    resources :notes, only: [:create, :update, :destroy]
    resources :organizations
    resources :people
    resources :projects do
      member do
        get :steps
        patch :change_date
        get :timeline
      end
    end
    resources :project_logs, path: 'logs'
    resources :project_steps do
      collection do
        patch :batch_destroy
        patch :adjust_dates
        patch :finalize
      end
      member do
        post :duplicate
        get :show_duplicate
      end
    end
    resources :project_groups

    resources :timeline_step_moves do
      member do
        patch :simple_move
      end
    end

    scope '/:attachable_type/:attachable_id' do
      resources :media
    end

    get 'settings' => 'settings#index'
    patch 'settings' => 'settings#update'

    namespace :accounting do
      resources :quickbooks do
        collection do
          get :authenticate
          get :oauth_callback
          get :disconnect
          get :full_sync
        end
      end

      resources :transactions
    end

    namespace :raw do
      resources :divisions
      resources :loans
      resources :organizations
      resources :people
      resources :project_steps
      resources :project_logs
      resources :notes
      resources :loan_question_sets
      resources :loan_questions
      resources :loan_response_sets
      post 'select_division', to: 'divisions#select'
    end

    get '/basic-projects/:id/:tab' => 'basic_projects#show', as: 'basic_project_tab'
    get 'dashboard' => 'dashboard#dashboard', as: 'dashboard'
    get '/loans/:id/:tab' => 'loans#show', as: 'loan_tab'
    get '/loans/:project_id/transactions/:id' => 'accounting/transactions#show', as: 'loan_transaction'
  end

  localized do
    resources :loans, only: [:index, :show]
    get 'loans/:id/gallery', to: 'loans#gallery', as: :gallery
  end

  get '/test' => 'static_pages#test'
  get '/ping', to: 'ping#index'

  root to: redirect(path: '/admin/dashboard')
end

app/views/layouts/admin/_custom_colors.html.slim
/ Custom colors defined per-division. These must be in a partial as if they are in a
/ scss file they will get cached in production so changes won't take effect without a server restart.
/ Most of the below are copied from Bootstrap by looking for things that are default color and copying
/ the style rules from the inspector.

- colors = admin_custom_colors # Helper method

style type="text/css"
  | /* Navbar and links */
    nav, nav a, nav a:hover, nav a:focus {
      color: #{colors[:banner_fg]};
      background-color: #{colors[:banner_bg]};
    }

    /* General links */
    a, .btn-link {
      color: #{colors[:accent_main]};
    }

    /* General links on hover */
    a:hover,
    a:focus,
    .btn-link:hover,
    .btn-link:focus {
      color: #{colors[:accent_darkened]};
    }

    /* Navbar toggle button lines */
    .navbar-toggle {
      border-color: #{colors[:banner_fg]};
    }
    .navbar-toggle:hover {
      background-color: #{colors[:banner_fg_transp]};
    }
    .navbar-toggle .icon-bar {
      background-color: #{colors[:banner_fg]};
    }

    /* Nav menu item background colors for mobile mode */
    .nav-xs .nav {
      background-color: #{colors[:banner_bg]};
    }
    .nav-xs .nav > li > a:hover,
    .nav-xs .nav > li > a:focus {
      background-color: #{colors[:banner_fg_transp]};
    }

    /* Progress bars, buttons, pagination */
    .progress-wrapper .progress-bar,
    .btn-primary,
    .pagination > .active > a,
    .pagination > .active > a:hover,
    .pagination > .active > a:focus,
    .pagination > .active > span,
    .pagination > .active > span:hover,
    .pagination > .active > span:focus,
    .table.rowlink .pagination > .active > a,
    .table.rowlink .pagination > .active > a:hover,
    .table.rowlink .pagination > .active > a:focus,
    .table.rowlink .pagination > .active > span,
    .table.rowlink .pagination > .active > span:hover,
    .table.rowlink .pagination > .active > span:focus {
      color: #{colors[:accent_fg_text]};
      background-color: #{colors[:accent_main]};
      border-color: #{colors[:accent_darkened]};
    }

    /* Buttons on hover */
    .btn-primary:hover,
    .btn-primary:active,
    .btn-primary:active:hover,
    .btn-primary:active:focus,
    .btn-primary:active.focus,
    .btn-primary.active:hover,
    .btn-primary.active:focus,
    .btn-primary.active.focus,
    .open > .btn-primary.dropdown-toggle:hover,
    .open > .btn-primary.dropdown-toggle:focus,
    .open > .btn-primary.dropdown-toggle.focus {
      color: #{colors[:accent_fg_text]};
      background-color: #{colors[:accent_darkened]};
    }

app/views/layouts/admin/_custom_colors.slim
/ Custom colors defined per-division. These must be in a partial as if they are in a
/ scss file they will get cached in production so changes won't take effect without a server restart.
/ Most of the below are copied from Bootstrap by looking for things that are default color and copying
/ the style rules from the inspector.

- colors = admin_custom_colors # Helper method

style type="text/css"
  | /* Navbar and links */
    nav, nav a, nav a:hover, nav a:focus {
      color: #{colors[:banner_fg]};
      background-color: #{colors[:banner_bg]};
    }

    /* General links */
    a, .btn-link {
      color: #{colors[:accent_main]};
    }

    /* General links on hover */
    a:hover,
    a:focus,
    .btn-link:hover,
    .btn-link:focus {
      color: #{colors[:accent_darkened]};
    }

    /* Navbar toggle button lines */
    .navbar-toggle {
      border-color: #{colors[:banner_fg]};
    }
    .navbar-toggle:hover {
      background-color: #{colors[:banner_fg_transp]};
    }
    .navbar-toggle .icon-bar {
      background-color: #{colors[:banner_fg]};
    }

    /* Nav menu item background colors for mobile mode */
    .nav-xs .nav {
      background-color: #{colors[:banner_bg]};
    }
    .nav-xs .nav > li > a:hover,
    .nav-xs .nav > li > a:focus {
      background-color: #{colors[:banner_fg_transp]};
    }

    /* Progress bars, buttons, pagination */
    .progress-wrapper .progress-bar,
    .btn-primary,
    .table.rowlink .pagination > .active > a,
    .table.rowlink .pagination > .active > a:hover,
    .table.rowlink .pagination > .active > a:focus,
    .table.rowlink .pagination > .active > span,
    .table.rowlink .pagination > .active > span:hover,
    .table.rowlink .pagination > .active > span:focus {
      color: #{colors[:accent_fg_text]};
      background-color: #{colors[:accent_main]};
      border-color: #{colors[:accent_darkened]};
    }

    /* Buttons on hover */
    .btn-primary:hover,
    .btn-primary:active,
    .btn-primary:active:hover,
    .btn-primary:active:focus,
    .btn-primary:active.focus,
    .btn-primary.active:hover,
    .btn-primary.active:focus,
    .btn-primary.active.focus,
    .open > .btn-primary.dropdown-toggle:hover,
    .open > .btn-primary.dropdown-toggle:focus,
    .open > .btn-primary.dropdown-toggle.focus {
      color: #{colors[:accent_fg_text]};
      background-color: #{colors[:accent_darkened]};
    }

app/views/layouts/admin/_division_brand.html.slim
/ The division logo/text area in the banner.
- division = selected_division
.division-brand.col-sm-4.col-xs-10
  - if division.present?
    - if division.logo.present?
      .with-logo class="#{division.try(:has_logo_text?) ? "with-text" : nil}"
        = image_tag division.logo.url(:banner)
        - if division.has_logo_text?
          .logo-text = division.logo_text
    - else
      .without-logo = division.logo_text || division.name
  - elsif size == "xs" # In 'sm' mode this gets shown elsewhere.
    .madeline-logo
      .ftc-triple-spiral
      .madeline Madeline

app/views/layouts/admin/_division_brand.slim
/ The division logo/text area in the banner.
- division = selected_division
.division-brand.col-sm-4.col-xs-10
  - if division.present?
    - if division.logo.present?
      .with-logo class="#{division.try(:has_logo_text?) ? "with-text" : nil}"
        = image_tag division.logo.url(:banner)
        - if division.has_logo_text?
          .logo-text = division.logo_text
    - else
      .without-logo = division.logo_text || division.name
  - elsif size == "xs" # In 'sm' mode this gets shown elsewhere.
    .madeline-logo
      .ftc-triple-spiral
      .madeline Madeline

app/views/layouts/admin/_page.html.slim
div
  - unless @header_disabled
    = render "layouts/admin/site_header"

  .sidemenu.container-fluid
    .row
      #navbar.sidebar
        ul.nav.nav-sidebar
          = render "layouts/admin/site_menu"
      .content-wrapper
        .alerts = render "application/alerts"
        section.content
          .page-header
            h1.page-title = yield :title
            .with-title = yield :with_title
          = yield

javascript:
  $(function() {
    new MS.Views.PageView();
  })

app/views/layouts/admin/_print.html.slim
div.visible-print-preview
  = render "application/alerts"

section.content

  .page-header
    h1.page-title = yield :title
    .with-title.visible-print-preview
      .btn.btn-primary data-action="print" = t('common.print')

  = yield

javascript:
  $(function() {
    new MS.Views.PageView();
    new MS.Views.PrintView();
  })

app/views/layouts/admin/_print.slim
div.visible-print-preview
  = render "application/alerts"

section.content

  .page-header
    h1.page-title = yield :title
    .with-title.visible-print-preview
      .btn.btn-primary data-action="print" = t('common.print')

  = yield

javascript:
  $(function() {
    new MS.Views.PageView();
    new MS.Views.PrintView();
  })

app/views/layouts/admin/_site_header.html.slim
- division = selected_division
nav.navbar-fixed-top

  / Navbar for sm devices (768px and above).
  .nav-sm.container-fluid
    .row.navbar-main
      .madeline-logo.col-sm-4
        .ftc-triple-spiral
        - unless division.present?
          .madeline Madeline

      = render("layouts/admin/division_brand", size: "sm")

      / This is the division menu, user profile link and logout button.
      .user-div-info.col-sm-4
        = render("layouts/admin/user_div_info", size: "sm")

  / Navbar for xs devices (767px and below)
  .nav-xs.container-fluid
    .navbar-main.row
      = render("layouts/admin/division_brand", size: "xs")
      .col-xs-2
        / Hamburger menu toggle.
        button.navbar-toggle aria-expanded="false" data-target="#navbar-menu" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar

    / This is the menu toggled by the toggle above.
    #navbar-menu.collapse.navbar-collapse
      ul.nav.navbar-nav
        = render "layouts/admin/site_menu"
        hr
        = render("layouts/admin/user_div_info", size: "xs")

app/views/layouts/admin/_site_menu.html.slim
li = link_to t('menu.dashboard'), admin_dashboard_path
li = link_to t('menu.loans'), admin_loans_path
li = link_to t('menu.logs'), admin_project_logs_path
li = link_to t('menu.coops'), admin_organizations_path
li = link_to t('menu.calendar'), admin_calendar_index_path
- if policy(Person).index?
  li = link_to t('menu.people'), admin_people_path
li = link_to t('menu.basic_projects'), admin_basic_projects_path
- if policy(:'accounting/transaction').index?
  li = link_to 'Transactions', admin_accounting_transactions_path

li
  a data-toggle="collapse" data-target=".submenu1" aria-expanded="false"
    => t('menu.manage')
    span.caret
  ul.nav.collapse.submenu.submenu1 role="menu"
    - if policy(Division).index?
      li = link_to t('menu.divisions'), admin_divisions_path
    li = link_to t('menu.loan_questions'), admin_loan_questions_path
    - if policy(:setting).index?
      li = link_to t('menu.settings'), admin_settings_path

app/views/layouts/admin/_user_div_info.slim
/ The user, division change, and logout links.
/ Used in both the right side of banner and in slide-down menu for mobile.
- division = selected_division
li
  = link_to "#", :"data-expands" => "division-dropdown"
    i.fa.fa-retweet>
    = t(division.nil? ? "template.select_division" : "template.change_division")
  = form_tag(select_admin_divisions_path, class: 'select_division_form') do
    = select_tag(:division_id,
      options_for_select(division_select_options, selected_division_id),
      class: 'form-control',
      :'data-expandable' => "division-dropdown")
    = hidden_field_tag(:redisplay_url)

li
  = link_to admin_person_path(current_user.profile), class: "profile-link",
    title: t("template.profile")
    i.fa.fa-user>
    = current_user.try(:name) || t("common.user")

li
  = link_to destroy_user_session_path, method: :delete, title: t("logout")
    i.fa.fa-sign-out>
    - if size == "xs"
      = t("logout")

app/views/layouts/admin/_user_menu.html.slim
li
  = link_to t("user.account"), admin_person_path(@current_user.profile)

li.divider role="separator"

li
  = link_to t("logout"), destroy_user_session_path, :method => :delete

app/views/layouts/admin/_user_menu.slim
li
  = link_to t("user.account"), admin_person_path(@current_user.profile)

li.divider role="separator"

li
  = link_to t("logout"), destroy_user_session_path, :method => :delete

app/views/layouts/admin/admin.html.slim
- if @print_view
  - content_for :content
    = render "layouts/admin/print"
- else
  - content_for :content
    = render "layouts/admin/page"

= render template: "layouts/base"

app/views/layouts/admin/admin.slim
- if @print_view
  - content_for :content
    = render "layouts/admin/print"
- else
  - content_for :content
    = render "layouts/admin/page"

= render template: "layouts/base"