config/routes.rb
Rails.application.routes.draw do
  # Disallow registration, wire up custom devise sessions controller
  devise_for :users, skip: [:registrations], controllers: { sessions: :sessions }

  devise_scope :user do
    # Manually re-creates routes for editing users
    get 'users/edit' => 'devise/registrations#edit', as: :edit_user_registration
    put 'users' => 'devise/registrations#update', as: :user_registration
  end

  namespace :admin do
    resources :basic_projects, path: 'basic-projects'
    resources :calendar, only: [:index]
    resources :calendar_events, only: [:index]
    resources :loan_response_sets
    resources :divisions do
      collection do
        post :select
      end
    end
    resources :loans do
      member do
        get :questionnaires
        get :print
        get :duplicate
      end
    end
    resources :loan_questions do
      patch 'move', on: :member
    end
    resources :notes, only: [:create, :update, :destroy]
    resources :organizations
    resources :people
    resources :projects do
      member do
        get :steps
        patch :change_date
        get :timeline
      end
    end
    resources :project_logs, path: 'logs'
    resources :project_steps do
      collection do
        patch :batch_destroy
        patch :adjust_dates
        patch :finalize
      end
      member do
        post :duplicate
        get :show_duplicate
      end
    end
    resources :project_groups

    resources :timeline_step_moves do
      member do
        patch :simple_move
      end
    end

    scope '/:attachable_type/:attachable_id' do
      resources :media
    end

    get 'settings' => 'settings#index'
    patch 'settings' => 'settings#update'

    namespace :accounting do
      resources :quickbooks do
        collection do
          get :authenticate
          get :oauth_callback
          get :disconnect
          get :full_sync
        end
      end

      resources :transactions
    end

    namespace :raw do
      resources :divisions
      resources :loans
      resources :organizations
      resources :people
      resources :project_steps
      resources :project_logs
      resources :notes
      resources :loan_question_sets
      resources :loan_questions
      resources :loan_response_sets
      post 'select_division', to: 'divisions#select'
    end

    get '/basic-projects/:id/:tab' => 'basic_projects#show', as: 'basic_project_tab'
    get 'dashboard' => 'dashboard#dashboard', as: 'dashboard'
    get '/loans/:id/:tab' => 'loans#show', as: 'loan_tab'
    get '/loans/:project_id/transactions/:id' => 'accounting/transactions#show', as: 'loan_transaction'
  end

  localized do
    resources :loans, only: [:index, :show]
    get 'loans/:id/gallery', to: 'loans#gallery', as: :gallery
  end

  get '/test' => 'static_pages#test'
  get '/ping', to: 'ping#index'

  root to: redirect(path: '/admin/dashboard')
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  alias              :string
#  city               :string
#  contact_notes      :text
#  country_id         :integer
#  created_at         :datetime         not null
#  custom_data        :json
#  division_id        :integer
#  email              :string
#  fax                :string
#  id                 :integer          not null, primary key
#  industry           :string
#  is_recovered       :boolean
#  last_name          :string
#  legal_name         :string
#  name               :string
#  neighborhood       :string
#  postal_code        :string
#  primary_contact_id :integer
#  primary_phone      :string
#  qb_id              :string
#  referral_source    :string
#  secondary_phone    :string
#  sector             :string
#  state              :string
#  street_address     :text
#  tax_no             :string
#  updated_at         :datetime         not null
#  website            :string
#
# Indexes
#
#  index_organizations_on_division_id  (division_id)
#
# Foreign Keys
#
#  fk_rails_0de9c8b6c9  (country_id => countries.id)
#  fk_rails_a43f2db6ae  (primary_contact_id => people.id)
#  fk_rails_e5fef62474  (division_id => divisions.id)
#

class Organization < ActiveRecord::Base
  include Contactable  # this is a placeholder concern for the shared aspects between Organization and People.
  include Notable
  include MediaAttachable
  include DivisionBased

  belongs_to :division
  belongs_to :country
  belongs_to :primary_contact, class_name: 'Person'

  has_many :loans, dependent: :destroy
  has_many :people, foreign_key: :primary_organization_id, dependent: :nullify

  validates :name, presence: true
  validates :division_id, presence: true

  validate :primary_contact_is_member

  def loans_count
    loans.size
  end

  def active_loans
    loans.where(status_value: Loan::STATUS_ACTIVE_VALUE)
  end

  private

  def primary_contact_is_member
    return if primary_contact.blank?
    return if person_ids.include?(primary_contact_id)

    errors.add(:primary_contact, :invalid)
  end

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < Admin::AdminController
  def index
    authorize Organization
    @organizations_grid = initialize_grid(
      policy_scope(Organization),
      include: [:country, :division, :primary_contact, :people],
      conditions: division_index_filter,
      order: 'name',
      custom_order: {
        "organizations.name" => "LOWER(organizations.name)",
        "organizations.city" => "LOWER(organizations.city)"
      },
      per_page: 50,
      name: 'organizations',
      enable_export_to_csv: true
    )

    @csv_mode = true
    @enable_export_to_csv = true

    export_grid_if_requested('organizations': 'organizations_grid_definition') do
      # This block only executes if CSV is not being returned
      @csv_mode = false
    end
  end

  # show view includes edit
  def show
    @org = Organization.find(params[:id])
    authorize @org
    prep_form_vars

    @new_note = Note.new(notable: @org)
    @new_note = nil unless Pundit.policy(current_user, @new_note).new?
  end

  def new
    @org = Organization.new(division: current_division)
    authorize @org
    prep_form_vars
  end

  def update
    @org = Organization.find(params[:id])
    authorize @org

    if @org.update(organization_params)
      redirect_to admin_organization_path(@org), notice: I18n.t(:notice_updated)
    else
      prep_form_vars
      render :show
    end
  end

  def create
    @org = Organization.new(organization_params)
    @org.division ||= current_division
    authorize @org

    if @org.save
      redirect_to admin_organization_path(@org), notice: I18n.t(:notice_created)
    else
      prep_form_vars
      render :new
    end
  end

  def destroy
    @org = Organization.find(params[:id])
    authorize @org

    if @org.destroy
      redirect_to admin_organizations_path, notice: I18n.t(:notice_deleted)
    else
      prep_form_vars
      render :show
    end
  end

  private

  def organization_params
    params.require(:organization).permit(
      :name, :street_address, :city, :state, :country_id, :neighborhood, :website,
      :alias, :email, :fax, :primary_phone, :secondary_phone, :tax_no,
      :industry, :sector, :referral_source, :contact_notes,
      :division_id, :primary_contact_id, person_ids: []
    )
  end

  def prep_form_vars
    @countries = Country.order(:name)
    @division_choices = division_choices
    @people_choices = person_policy_scope(Person.all).order(:name)
    @notes = @org.notes.order(created_at: :desc)

    @loans_grid = initialize_grid(
      @org.active_loans,
      order: 'projects.signing_date',
      order_direction: 'desc',
      name: 'loans',
      per_page: 10
    )
  end
end

app/views/admin/organizations/_form.html.slim
= simple_form_for([:admin, @org],
    html: { \
      class: 'form-horizontal organization-record',
    },
    wrapper: :horizontal_form_condensed,
    defaults: { \
      input_html: {class: 'form-element form-control'},
    },
  ) do |f|

  = error_notification(f)

  = f.input :division
    - if policy(@org).reassign_division?
      .view-element
        - if @org.division
          = link_to @org.division.name, admin_division_path(@org.division)
      = f.input_field :division_id, collection: @division_choices, include_blank: false
    - else
      = @org.division.try(:name)

  = f.input :name
    .view-element = @org.name
    = f.input_field :name

  = f.input :legal_name
    .view-element = @org.legal_name
    = f.input_field :legal_name

  = f.input :primary_phone
    .view-element = @org.primary_phone
    = f.input_field :primary_phone

  = f.input :secondary_phone
    .view-element = @org.secondary_phone
    = f.input_field :secondary_phone

  = f.input :fax
    .view-element = @org.fax
    = f.input_field :fax

  = f.input :email
    .view-element = @org.email
    = f.input_field :email

  = f.input :street_address
    .view-element = @org.street_address
    = f.input_field :street_address, as: :text

  = f.input :neighborhood
    .view-element = @org.neighborhood
    = f.input_field :neighborhood

  = f.input :city
    .view-element = @org.city
    = f.input_field :city

  = f.input :state
    .view-element = @org.state
    = f.input_field :state

  = f.input :country
    .view-element = @org.country.try(:name)
    = f.input_field :country_id, collection: @countries, include_blank: true

  = f.input :website
    - unless @org.website.nil?
      .view-element = link_to(@org.website, urlify(@org.website), target: '_blank')
    = f.input_field :website

  = f.input :sector
    .view-element = @org.sector
    = f.input_field :sector

  = f.input :tax_no
    .view-element = @org.tax_no
    = f.input_field :tax_no

  = f.input :alias
    .view-element = @org.alias
    = f.input_field :alias

  = f.input :industry
    .view-element = @org.industry
    = f.input_field :industry

  = f.input :referral_source
    .view-element = @org.referral_source
    = f.input_field :referral_source

  = f.input :contact_notes
    .view-element = @org.contact_notes
    = f.input_field :contact_notes

  = f.input :primary_contact
    .view-element
      - if @org.primary_contact
        = link_to @org.primary_contact.name, admin_person_path(@org.primary_contact)
    = f.input_field :primary_contact_id, collection: @people_choices, include_blank: true

  = f.input :people
    .view-element style=""
      - @org.people.each do |person|
        = link_to person.name, admin_person_path(person)
        br
    .form-element
      = f.association :people, label: false, collection: @people_choices, include_blank: true

  .actions.form-element
    - unless @org.new_record?
      - if @org.valid?
        a.btn.btn-default.show-action = t(:cancel)
      - else
        a.btn.btn-default href=admin_organization_path(@org) = t(:cancel)
    = f.submit class: 'update-action btn btn-primary'
  .clearfix

javascript:
  $(function() { $('#organization_person_ids').select2(); });

app/views/admin/organizations/_form.slim
= simple_form_for([:admin, @org],
    html: { \
      class: 'form-horizontal organization-record',
    },
    wrapper: :horizontal_form_condensed,
    defaults: { \
      input_html: {class: 'form-element form-control'},
    },
  ) do |f|

  = error_notification(f)

  = f.input :division
    - if policy(@org).reassign_division?
      .view-element
        - if @org.division
          = link_to @org.division.name, admin_division_path(@org.division)
      = f.input_field :division_id, collection: @division_choices, include_blank: false
    - else
      = @org.division.try(:name)

  = f.input :name
    .view-element = @org.name
    = f.input_field :name

  = f.input :legal_name
    .view-element = @org.legal_name
    = f.input_field :legal_name

  = f.input :primary_phone
    .view-element = @org.primary_phone
    = f.input_field :primary_phone

  = f.input :secondary_phone
    .view-element = @org.secondary_phone
    = f.input_field :secondary_phone

  = f.input :fax
    .view-element = @org.fax
    = f.input_field :fax

  = f.input :email
    .view-element = @org.email
    = f.input_field :email

  = f.input :primary_contact
    .view-element
      - if @org.primary_contact
        = link_to @org.primary_contact.name, admin_person_path(@org.primary_contact)
    = f.input_field :primary_contact_id, collection: @contact_choices, include_blank: true

  = f.input :street_address
    .view-element = @org.street_address
    = f.input_field :street_address, as: :text

  = f.input :neighborhood
    .view-element = @org.neighborhood
    = f.input_field :neighborhood

  = f.input :city
    .view-element = @org.city
    = f.input_field :city

  = f.input :state
    .view-element = @org.state
    = f.input_field :state

  = f.input :country
    .view-element = @org.country.try(:name)
    = f.input_field :country_id, collection: @countries, include_blank: true

  = f.input :website
    - unless @org.website.nil?
      .view-element = link_to(@org.website, urlify(@org.website), target: '_blank')
    = f.input_field :website

  = f.input :sector
    .view-element = @org.sector
    = f.input_field :sector

  = f.input :tax_no
    .view-element = @org.tax_no
    = f.input_field :tax_no

  = f.input :alias
    .view-element = @org.alias
    = f.input_field :alias

  = f.input :industry
    .view-element = @org.industry
    = f.input_field :industry

  = f.input :referral_source
    .view-element = @org.referral_source
    = f.input_field :referral_source

  = f.input :contact_notes
    .view-element = @org.contact_notes
    = f.input_field :contact_notes

  = f.input :people
    .view-element style=""
      - @org.people.each do |person|
        = link_to person.name, admin_person_path(person)
        br
    .form-element
      = f.association :people, label: false, collection: @people_choices, include_blank: true

  .actions.form-element
    - unless @org.new_record?
      - if @org.valid?
        a.btn.btn-default.show-action = t(:cancel)
      - else
        a.btn.btn-default href=admin_organization_path(@org) = t(:cancel)
    = f.submit class: 'update-action btn btn-primary'
  .clearfix

javascript:
  $(function() { $('#organization_person_ids').select2(); });

app/views/admin/organizations/_loans.html.slim
.header-with-links
  h1 = t('organization.active_loans')
  = link_to t(".view_all_loans"), admin_loans_path(loans: {f:{status_value: '', organization_id: @org.id}})
  = link_to t("loan.shared.new"), new_admin_loan_path(organization_id: @org.id), class: 'new-link'

= grid(@loans_grid, show_filters: :no, html: {class: 'rowlink table-hover', data: {link: 'row'}}) do |g|

  - g.blank_slate t("common.no_records")

  - g.column name: t("id"), attribute: 'id', filter: false, in_csv: false do |loan|
    - link_to(loan.id, admin_loan_path(loan.id))

  - g.column name: t("loan.sign_date"), attribute: 'signing_date' do |loan|
    - loan.signing_date ? l(loan.signing_date) : ''

  - g.column name: t("status"), attribute: 'status_value' do |loan|
    - loan.status

  - g.column name: t("loan.loan_type"), attribute: 'loan_type_value' do |loan|
    - loan.loan_type

  - g.column name: t("loan.amount"), attribute: 'amount' do |loan|
    - format_currency(loan.amount, loan.currency, tooltip: false)

  - g.column name: t("details") do |loan|
    - loan.details

app/views/admin/organizations/_loans.slim
.header-with-links
  h1 = t('organization.active_loans')
  = link_to t(".view_all_loans"), admin_loans_path('loans[f][organizations.name][]' => @org.name)
  = link_to t("loan.shared.new"), new_admin_loan_path(organization_id: @org.id), class: 'btn btn-default new-button'

= grid(@loans_grid, show_filters: :no, html: {class: 'rowlink table-hover', data: {link: 'row'}}) do |g|

  - g.blank_slate t("common.no_records")

  - g.column name: t("id"), attribute: 'id', filter: false, in_csv: false do |loan|
    - link_to(loan.id, admin_loan_path(loan.id))

  - g.column name: t("loan.sign_date"), attribute: 'signing_date' do |loan|
    - loan.signing_date ? l(loan.signing_date) : ''

  - g.column name: t("status"), attribute: 'status_value' do |loan|
    - loan.status

  - g.column name: t("loan.loan_type"), attribute: 'loan_type_value' do |loan|
    - loan.loan_type

  - g.column name: t("loan.amount"), attribute: 'amount' do |loan|
    - number_to_currency(loan.amount)

  - g.column name: t("details") do |loan|
    - loan.details

app/views/admin/organizations/_organizations_grid.html.slim
= define_grid(@organizations_grid, show_filters: :show, hide_csv_button: true,
    html: {class: 'rowlink table-hover', data: {link: @csv_mode ? nil : 'row'}}) do |g|

    - g.blank_slate do
      - @empty_list = true
      - content_tag(:div, t('common.no_records'), class: 'alert alert-info')

    - g.column name: t('common.id'), attribute: 'id', filter: false, in_csv: false do |organization|
      - link_to(organization.id, admin_organization_path(organization.id))
    - g.column name: csv_id, attribute: 'id', in_html: false, filter: false
    - g.column name: t('common.division'), attribute: 'name', assoc: :division, in_html: false, filter: false
    - g.column name: t('common.name'), attribute: 'name', detach_with_id: :name_filter
    - g.column name: t('activerecord.attributes.organization.legal_name'), attribute: 'legal_name',
      in_html: false, filter: false
    
    - g.column name: t('activerecord.attributes.organization.primary_phone'),
      attribute: 'primary_phone', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.secondary_phone'),
      attribute: 'secondary_phone', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.fax'), attribute: 'fax',
      in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.email'), attribute: 'email',
      in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.primary_contact'), attribute: 'name',
      assoc: :primary_contact, in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.street_address'),
      attribute: 'street_address', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.neighborhood'),
      attribute: 'neighborhood', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.city'), attribute: 'city',
      detach_with_id: :city_filter, custom_filter: :auto
    - g.column name: t('activerecord.attributes.organization.state'), attribute: 'state',
      in_html: false, filter: false
    - g.column name:  t('activerecord.attributes.organization.country'), attribute: 'name', assoc: :country,
      custom_filter: :auto, detach_with_id: :country_filter do |organization|
      - organization.country.try(:name)

    - g.column name: t('activerecord.attributes.organization.website'), attribute: 'website', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.sector'), attribute: 'sector', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.tax_no'), attribute: 'sector', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.alias'), attribute: 'alias', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.industry'), attribute: 'industry', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.referral_source'), attribute: 'referral_source', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.contact_notes'), attribute: 'contact_notes', in_html: false, filter: false
    
    - g.column name: t('activerecord.attributes.organization.additional_people'), attribute: 'name',
      assoc: :people, table_alias: 'members', in_html: false, filter: false do |organization|
      - if organization.people.length > 0
        - organization.people.collect{|person| person[:name]}.to_sentence
    
    - g.column name: t('activerecord.attributes.organization.active_loans'),
      in_html: false, filter: false do |organization|
      - if organization.active_loans.length > 0
        - organization.active_loans.collect{|loan| loan[:name]}.to_sentence
  
    - g.column name: t('common.created'), attribute: 'created_at', filter: false,
      in_csv: false do |organization|
      - fuzzy_time(organization.created_at)
    - g.column name: t('common.created'), attribute: 'created_at', in_html: false, filter: false

    - g.column name: t('common.updated'), attribute: 'updated_at', filter: false,
      in_csv: false do |organization|
      - fuzzy_time(organization.updated_at)
    - g.column name: t('common.updated'), attribute: 'updated_at', in_html: false, filter: false

app/views/admin/organizations/_organizations_grid.slim
= define_grid(@organizations_grid, show_filters: :show, hide_csv_button: true,
    html: {class: 'rowlink table-hover', data: {link: @csv_mode ? nil : 'row'}}) do |g|

    - g.blank_slate do
      - @empty_list = true
      - content_tag(:div, t('common.no_records'), class: 'alert alert-info')

    - g.column name: t('common.id'), attribute: 'id', filter: false, in_csv: false do |organization|
      - link_to(organization.id, admin_organization_path(organization.id))
    - g.column name: csv_id, attribute: 'id', in_html: false, filter: false
    - g.column name: t('common.division'), attribute: 'name', assoc: :division, in_html: false, filter: false
    - g.column name: t('common.name'), attribute: 'name', detach_with_id: :name_filter
    - g.column name: t('activerecord.attributes.organization.legal_name'), attribute: 'legal_name',
      in_html: false, filter: false
    
    - g.column name: t('activerecord.attributes.organization.primary_phone'),
      attribute: 'primary_phone', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.secondary_phone'),
      attribute: 'secondary_phone', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.fax'), attribute: 'fax',
      in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.email'), attribute: 'email',
      in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.primary_contact'), attribute: 'name',
      assoc: :primary_contact, in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.street_address'),
      attribute: 'street_address', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.neighborhood'),
      attribute: 'neighborhood', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.city'), attribute: 'city',
      detach_with_id: :city_filter, custom_filter: :auto
    - g.column name: t('activerecord.attributes.organization.state'), attribute: 'state',
      in_html: false, filter: false
    - g.column name:  t('activerecord.attributes.organization.country'), attribute: 'name', assoc: :country,
      custom_filter: :auto, detach_with_id: :country_filter do |organization|
      - organization.country.try(:name)

    - g.column name: t('activerecord.attributes.organization.website'), attribute: 'website', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.sector'), attribute: 'sector', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.tax_no'), attribute: 'sector', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.alias'), attribute: 'alias', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.industry'), attribute: 'industry', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.referral_source'), attribute: 'referral_source', in_html: false, filter: false
    - g.column name: t('activerecord.attributes.organization.contact_notes'), attribute: 'contact_notes', in_html: false, filter: false
    
    - g.column name: t('activerecord.attributes.organization.additional_people'), attribute: 'name',
      assoc: :people, table_alias: 'members', in_html: false, filter: false do |organization|
      - if organization.people.length > 0
        - organization.people.collect{|person| person[:name]}.to_sentence
    
    - g.column name: t('activerecord.attributes.organization.active_loans'),
      in_html: false, filter: false do |organization|
      - if organization.active_loans.length > 0
        - organization.active_loans.collect{|loan| loan[:name]}.to_sentence
  
    - g.column name: t('common.created'), attribute: 'created_at', filter: false,
      in_csv: false do |organization|
      - fuzzy_time(organization.created_at)
    - g.column name: t('common.created'), attribute: 'created_at', in_html: false, filter: false

    - g.column name: t('common.updated'), attribute: 'updated_at', filter: false,
      in_csv: false do |organization|
      - fuzzy_time(organization.updated_at)
    - g.column name: t('common.updated'), attribute: 'updated_at', in_html: false, filter: false

app/views/admin/organizations/grid_slim.html.slim
= define_grid(@organizations_grid) do |g|

  /= render "grid_content", g: g
  
  - g.blank_slate do
    - @empty_list = true
    - content_tag(:div, t("no_records"), class: 'alert alert-info')

  - g.column name: t("id"), attribute: 'id', filter: false, in_csv: false do |organization|
    - link_to(organization.id, admin_organization_path(organization.id))

  - g.column name: t("id"), attribute: 'id', in_html: false do |organization|
    - organization.id

  - g.column name: t("name"), attribute: 'name', detach_with_id: :name_filter do |organization|
    - organization.name

  - g.column name: t("city"), attribute: 'city', detach_with_id: :city_filter,
    custom_filter: :auto do |organization|
    - organization.city

  - g.column name: t("country"), attribute: 'name', assoc: :country,
    custom_filter: :auto, detach_with_id: :country_filter, in_csv: false do |organization|
    - organization.country.try(:name)

  - g.column name: t("created"), attribute: 'created_at', filter: false,
    in_csv: false do |organization|
    - fuzzy_time(organization.created_at)

  - g.column name: t("created"), attribute: 'created_at', in_html: false do |organization|
    - organization.created_at

  - g.column name: t("updated"), attribute: 'updated_at', filter: false,
    in_csv: false do |organization|
    - fuzzy_time(organization.updated_at)

  - g.column name: t("updated"), attribute: 'updated_at', in_html: false do |organization|
    - organization.updated_at

app/views/admin/organizations/index.html.slim
- content_for(:title, t("coops"))

- content_for :with_title
  = link_to t("organization.new"), new_admin_organization_path, class: 'btn btn-default new-button'

= render "organizations_grid_definition"

- unless @organizations_grid.no_records_at_all
  header.block.index-table
    .filters
      h4 = t("filter_by")

      .larger-text-box.filter
        label = t("name")
        .filter-content
          = grid_filter(@organizations_grid, :name_filter)

      .filter
        label = t("city")
        .filter-content
          = grid_filter(@organizations_grid, :city_filter)

      .filter
        label = t("country")
        .filter-content
          = grid_filter(@organizations_grid, :country_filter)

      .actions
        button.btn.btn-link.wg-external-reset-button data-grid-name="organizations"
          = t("clear")

        button.btn.btn-primary.wg-external-submit-button.action data-grid-name="organizations"
          = t("filter")
      .clearfix

= render_index_grid(@organizations_grid)

app/views/admin/organizations/index.slim
- content_for(:title, t("coops"))

- content_for :with_title
  = link_to t("organization.new"), new_admin_organization_path, class: 'btn btn-default new-button'

= render "organizations_grid"

- unless @empty_list
  header.block.index-table
    .filters
      h4 = t("filter_by")

      .larger-text-box.filter
        label = t("name")
        .filter-content
          = grid_filter(@organizations_grid, :name_filter)

      .filter
        label = t("city")
        .filter-content
          = grid_filter(@organizations_grid, :city_filter)

      .filter
        label = t("country")
        .filter-content
          = grid_filter(@organizations_grid, :country_filter)

      .actions
        button.btn.btn-link.wg-external-reset-button data-grid-name="organizations"
          = t("clear")

        button.btn.btn-primary.wg-external-submit-button.action data-grid-name="organizations"
          = t("filter")
      .clearfix

= render_index_grid(@organizations_grid)

app/views/admin/organizations/new.html.slim
- content_for(:title, t('organization.new'))

section.coop.new-view

  section.block
    = render 'form'

app/views/admin/organizations/new.slim
- content_for(:title, t(:new_thing, thing: t(:coop)))

section.coop.new-view

  section.block
    = render 'form'

app/views/admin/organizations/show.html.slim
- content_for(:title, @org.name)

section.coop.details

  section.block.coop-fields class=(@org.valid? ? 'show-view' : 'edit-view')
    .show-actions
      a href=admin_project_logs_path(org: @org.id)
        = t('common.view_logs')
        
      - if @org.valid?
        a.edit-action.view-element
          i.fa.fa-pencil.fa-large>
          = t("organization.edit")
        a.show-action.form-element
          = t("cancel_edit")
      - else
        a href=admin_organization_path(@org) = t("cancel_edit")
      
      / TODO: Confirm and cancel should have defaults (already done?)
      = link_to [:admin, @org], method: :delete,
          data: { \
            confirm: t('organization.confirm_deletion'),
            "confirm-title": t("organization.delete"),
          }
        i.fa.fa-trash.fa-large>
        = t("organization.delete")
    = render 'form'

  section.block
    = render 'loans'

  section.block
    h1 = t('organization.media')
    .row = render "admin/media/index", owner: @org

  section.block
    = render "admin/notes/notes_section"

= render "admin/media/modal"

javascript:
  $(function() { 
    new MS.Views.NotableView({ el: '.coop' });
    new MS.Views.ShowEditView({ el: '.coop-fields' });
  });