config/routes.rb
Rails.application.routes.draw do
  # Disallow registration, wire up custom devise sessions controller
  devise_for :users, skip: [:registrations], controllers: { sessions: :sessions }

  devise_scope :user do
    # Manually re-creates routes for editing users
    get 'users/edit' => 'devise/registrations#edit', as: :edit_user_registration
    put 'users' => 'devise/registrations#update', as: :user_registration
  end

  namespace :admin do
    resources :basic_projects, path: 'basic-projects'
    resources :calendar, only: [:index]
    resources :calendar_events, only: [:index]
    resources :loan_response_sets
    resources :divisions do
      collection do
        post :select
      end
    end
    resources :loans do
      member do
        get :questionnaires
        get :print
        get :duplicate
      end
    end
    resources :loan_questions do
      patch 'move', on: :member
    end
    resources :notes, only: [:create, :update, :destroy]
    resources :organizations
    resources :people
    resources :projects do
      member do
        get :steps
        patch :change_date
        get :timeline
      end
    end
    resources :project_logs, path: 'logs'
    resources :project_steps do
      collection do
        patch :batch_destroy
        patch :adjust_dates
        patch :finalize
      end
      member do
        post :duplicate
        get :show_duplicate
      end
    end
    resources :project_groups

    resources :timeline_step_moves do
      member do
        patch :simple_move
      end
    end

    scope '/:attachable_type/:attachable_id' do
      resources :media
    end

    get 'settings' => 'settings#index'
    patch 'settings' => 'settings#update'

    namespace :accounting do
      resources :quickbooks do
        collection do
          get :authenticate
          get :oauth_callback
          get :disconnect
          get :full_sync
        end
      end

      resources :transactions
    end

    namespace :raw do
      resources :divisions
      resources :loans
      resources :organizations
      resources :people
      resources :project_steps
      resources :project_logs
      resources :notes
      resources :loan_question_sets
      resources :loan_questions
      resources :loan_response_sets
      post 'select_division', to: 'divisions#select'
    end

    get '/basic-projects/:id/:tab' => 'basic_projects#show', as: 'basic_project_tab'
    get 'dashboard' => 'dashboard#dashboard', as: 'dashboard'
    get '/loans/:id/:tab' => 'loans#show', as: 'loan_tab'
    get '/loans/:project_id/transactions/:id' => 'accounting/transactions#show', as: 'loan_transaction'
  end

  localized do
    resources :loans, only: [:index, :show]
    get 'loans/:id/gallery', to: 'loans#gallery', as: :gallery
  end

  get '/test' => 'static_pages#test'
  get '/ping', to: 'ping#index'

  root to: redirect(path: '/admin/dashboard')
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::AdminController

  def index
    authorize :setting

    @division = current_division.root
    @accounts = ::Accounting::Account.all if @division.quickbooks_connected?
    @last_updated_at = @division.qb_connection.last_updated_at if @division.quickbooks_connected?
  end

  def update
    authorize :setting

    @division = current_division.root
    if @division.update(settings_params)
      redirect_to admin_settings_path, notice: I18n.t(:notice_updated)
    else
      @accounts = ::Accounting::Account.all if @division.quickbooks_connected?
      render :index
    end
  end

  def settings_params
    params.require(:division).permit(:principal_account_id, :interest_receivable_account_id,
      :interest_income_account_id)
  end
end

app/views/admin/settings/index.html.slim
- content_for(:title, t("settings.settings"))

script type="text/javascript" src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere-1.3.3.js"

javascript:
  intuit.ipp.anywhere.setup({menuProxy: '/path/to/blue-dot', grantUrl: '#{authenticate_admin_accounting_quickbooks_url}'});

section.block
  h2 = t("quickbooks.connection.connection")

  = simple_form_for([:admin, @division],
      url: admin_settings_path,
      method: 'patch',
      html: {class: 'form-horizontal'},
      wrapper: :horizontal_form_expanded,
    ) do |f|

    = f.input "connection_status" do
      .read-only
        - if Division.root && Division.root.quickbooks_connected?
          = t("quickbooks.connection.connected")
        - else
          = t("quickbooks.connection.not_connected")
    - if Division.root && Division.root.quickbooks_connected?
      = f.input "disconnect" do
        .read-only
          = link_to(t("quickbooks.connection.disconnect"),
            disconnect_admin_accounting_quickbooks_path)
      = f.input "last_updated_at" do
        .read-only
          - if @last_updated_at
            = l(@last_updated_at, format: :long)
          - else
            = t("quickbooks.connection.never_synced")
      = f.input "full_sync" do
        .read-only
          = link_to(t("quickbooks.connection.full_sync"),
            full_sync_admin_accounting_quickbooks_path)
    - else
      = f.input "connect" do
        / this will display a button that the user clicks to start the flow
        ipp:connectToIntuit

- if @accounts && !@accounts.empty?
  section.block
    h2 = t("quickbooks.accounts.accounts")
    p.note = t("quickbooks.accounts.note")

    = simple_form_for([:admin, @division],
        url: admin_settings_path,
        method: 'patch',
        html: {class: 'form-horizontal'},
        wrapper: :horizontal_form_expanded,
      ) do |f|

      = error_notification(f)
      = f.input :principal_account_id, collection: @accounts
      = f.input :interest_receivable_account_id, collection: @accounts
      = f.input :interest_income_account_id, collection: @accounts

      .text-right
        = f.submit t(:save), class: "btn btn-primary"

  section.alert.alert-warning
    = t('quickbooks.class_location_notice_html')